/*******************************************************************************
 * Copyright (c) 2025 Tlcsdm. All rights reserved.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution,
 * and is available at https://www.eclipse.org/legal/epl-v20.html
 ******************************************************************************/
package com.tlcsdm.eclipse.graphiti.demo.preferences;

/**
 * Constants for LVGL preferences.
 */
public class LvglPreferenceConstants {

	/** Preference key for the license header */
	public static final String PREF_LICENSE_HEADER = "licenseHeader";

	/** Default license header */
	public static final String DEFAULT_LICENSE_HEADER = 
			"/*\n" +
			" * Generated by LVGL UI Designer\n" +
			" * https://github.com/tlcsdm/eclipse-graphiti-example\n" +
			" */";

	private LvglPreferenceConstants() {
		// Prevent instantiation
	}
}
